In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

from deep_hedging import (
    Frequency,
    ConstantRateCurve,
    ZeroCouponBond,
    FixedCouponBond,
)

RANDOM_SEED = 12

In [3]:
RF_RATE = 0.15
Z_SPREAD = 0.05
CONVENIENCE_YIELD = 0.02

TIME_TILL_MATURITY = 2.0
FREQUENCY = Frequency.ANNUALLY

Equations:
1) $x_1 + x_2 = 1$
2) $x_2 \cdot (1 + rf + z) - cpn \cdot (1 + rf - cy) = 0$
3) $x_1 \cdot (1 + rf + z)^2 - (1 + cpn) \cdot (1 + rf - cy)^2 = 0$

Equations:
1) $x_1 + x_2 = 1$
2) $x_2 \cdot (1 + rf + z) - cpn \cdot (1 + rf - cy) = 0$
3) $x_1 \cdot (1 + rf + z)^2 - cpn \cdot (1 + rf - cy)^2 = (1 + rf - cy)^2$

In [4]:
k = np.array(
    [
        [1, 1, 0],
        [0, (1 + RF_RATE + Z_SPREAD), -(1 + RF_RATE - CONVENIENCE_YIELD)],
        [(1 + RF_RATE + Z_SPREAD) ** 2, 0, -((1 + RF_RATE - CONVENIENCE_YIELD) ** 2)],
    ]
)
y = np.array([1, 0, (1 + RF_RATE - CONVENIENCE_YIELD) ** 2])

In [5]:
k

array([[ 1.    ,  1.    ,  0.    ],
       [ 0.    ,  1.2   , -1.13  ],
       [ 1.44  ,  0.    , -1.2769]])

In [6]:
y

array([1.    , 0.    , 1.2769])

In [7]:
x = np.linalg.solve(k, y)
x

array([0.94166667, 0.05833333, 0.0619469 ])